name             'zip_zookeeper'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures zip_zookeeper'
long_description 'Installs/Configures zip_zookeeper'
version          '0.1.4'

depends 'java'
depends 'zookeeper'
