name             'ao_zookeeper'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures ao_zookeeper'
long_description 'Installs/Configures ao_zookeeper'
version          '0.1.16'

depends 'java'
depends 'zookeeper'
