node.default['java']['jdk_version'] = '8'
node.default["zookeeper"]["myid"] = '-1'
node.default["zookeeper"]["service_style"] = 'runit'
node.default["zookeeper"]["version"] = '3.4.6'
node.default["zookeeper"]["checksum"] = '971c379ba65714fd25dc5fe8f14e9ad1'
